matrix:
  include:
    - language: java
      script:
        - ant compile

    - language: shell
      before_install:
        - cd scripts/ 
      script:
        - bash -c 'shopt -s globstar nullglob; shellcheck ./*.{sh,ksh,bash}' 

notifications:
  email: false


